// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/emoji/pb/emoji.proto

package emojipb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmojizeRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojizeRequest) Reset()         { *m = EmojizeRequest{} }
func (m *EmojizeRequest) String() string { return proto.CompactTextString(m) }
func (*EmojizeRequest) ProtoMessage()    {}
func (*EmojizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8016ac399ca139d3, []int{0}
}

func (m *EmojizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojizeRequest.Unmarshal(m, b)
}
func (m *EmojizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojizeRequest.Marshal(b, m, deterministic)
}
func (m *EmojizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojizeRequest.Merge(m, src)
}
func (m *EmojizeRequest) XXX_Size() int {
	return xxx_messageInfo_EmojizeRequest.Size(m)
}
func (m *EmojizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmojizeRequest proto.InternalMessageInfo

func (m *EmojizeRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type EmojizeReply struct {
	EmojizedText         string   `protobuf:"bytes,1,opt,name=emojized_text,json=emojizedText,proto3" json:"emojized_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojizeReply) Reset()         { *m = EmojizeReply{} }
func (m *EmojizeReply) String() string { return proto.CompactTextString(m) }
func (*EmojizeReply) ProtoMessage()    {}
func (*EmojizeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8016ac399ca139d3, []int{1}
}

func (m *EmojizeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojizeReply.Unmarshal(m, b)
}
func (m *EmojizeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojizeReply.Marshal(b, m, deterministic)
}
func (m *EmojizeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojizeReply.Merge(m, src)
}
func (m *EmojizeReply) XXX_Size() int {
	return xxx_messageInfo_EmojizeReply.Size(m)
}
func (m *EmojizeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojizeReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmojizeReply proto.InternalMessageInfo

func (m *EmojizeReply) GetEmojizedText() string {
	if m != nil {
		return m.EmojizedText
	}
	return ""
}

func init() {
	proto.RegisterType((*EmojizeRequest)(nil), "emoji.EmojizeRequest")
	proto.RegisterType((*EmojizeReply)(nil), "emoji.EmojizeReply")
}

func init() { proto.RegisterFile("src/emoji/pb/emoji.proto", fileDescriptor_8016ac399ca139d3) }

var fileDescriptor_8016ac399ca139d3 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x2e, 0x4a, 0xd6,
	0x4f, 0xcd, 0xcd, 0xcf, 0xca, 0xd4, 0x2f, 0x48, 0x82, 0x30, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x58, 0xc1, 0x1c, 0x25, 0x15, 0x2e, 0x3e, 0x57, 0x10, 0xa3, 0x2a, 0x35, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0xa5, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x56, 0x32, 0xe6, 0xe2, 0x81, 0xab, 0x2a, 0xc8, 0xa9, 0x14, 0x52, 0xe6,
	0xe2, 0x4d, 0x85, 0xf0, 0x53, 0xe2, 0x91, 0x14, 0xf3, 0xc0, 0x04, 0x43, 0x52, 0x2b, 0x4a, 0x8c,
	0x5c, 0xa1, 0x9a, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x4c, 0xb9, 0xd8, 0xa1, 0x86,
	0x08, 0x89, 0xea, 0x41, 0x9c, 0x82, 0x6a, 0xb5, 0x94, 0x30, 0xba, 0x70, 0x41, 0x4e, 0xa5, 0x13,
	0x67, 0x14, 0x3b, 0x58, 0xb4, 0x20, 0x29, 0x89, 0x0d, 0xec, 0x74, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x76, 0x6d, 0x0b, 0x4a, 0xd6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmojiServiceClient is the client API for EmojiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmojiServiceClient interface {
	Emojize(ctx context.Context, in *EmojizeRequest, opts ...grpc.CallOption) (*EmojizeReply, error)
}

type emojiServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmojiServiceClient(cc *grpc.ClientConn) EmojiServiceClient {
	return &emojiServiceClient{cc}
}

func (c *emojiServiceClient) Emojize(ctx context.Context, in *EmojizeRequest, opts ...grpc.CallOption) (*EmojizeReply, error) {
	out := new(EmojizeReply)
	err := c.cc.Invoke(ctx, "/emoji.EmojiService/Emojize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmojiServiceServer is the server API for EmojiService service.
type EmojiServiceServer interface {
	Emojize(context.Context, *EmojizeRequest) (*EmojizeReply, error)
}

// UnimplementedEmojiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmojiServiceServer struct {
}

func (*UnimplementedEmojiServiceServer) Emojize(ctx context.Context, req *EmojizeRequest) (*EmojizeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Emojize not implemented")
}

func RegisterEmojiServiceServer(s *grpc.Server, srv EmojiServiceServer) {
	s.RegisterService(&_EmojiService_serviceDesc, srv)
}

func _EmojiService_Emojize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmojizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmojiServiceServer).Emojize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emoji.EmojiService/Emojize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmojiServiceServer).Emojize(ctx, req.(*EmojizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmojiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "emoji.EmojiService",
	HandlerType: (*EmojiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emojize",
			Handler:    _EmojiService_Emojize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/emoji/pb/emoji.proto",
}
